import React from 'react';
import {
    AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer
} from 'recharts';
import {
    Scale, Truck, AlertTriangle, TrendingUp, Calendar, MapPin, BrainCircuit
} from 'lucide-react';
import type { DashboardStats, Ticket } from '../types';

interface ExecutiveReportProps {
    stats: DashboardStats;
    chartData: any;
    topSuppliers: { name: string; value: number }[];
    gradeCIssues: Ticket[];
    aiInsight: string;
    generatedAt: string;
}

const ExecutiveReportTemplate: React.FC<ExecutiveReportProps> = ({
    stats, chartData, topSuppliers, gradeCIssues, aiInsight, generatedAt
}) => {
    return (
        <div
            id="executive-report"
            className="bg-white text-slate-800 p-8 w-[800px] min-h-[1123px] relative" // Fixed width for A4 consistency
            style={{ fontFamily: 'Inter, sans-serif' }}
        >
            {/* HEADER */}
            <div className="flex justify-between items-start border-b-2 border-slate-800 pb-4 mb-6">
                <div>
                    <h1 className="text-2xl font-bold uppercase tracking-widest text-slate-900">Laporan Eksekutif Harian</h1>
                    <p className="text-sm text-slate-500 font-medium">PT. SAWIT MAKMUR ABADI - Logistik & Supply Chain</p>
                </div>
                <div className="text-right">
                    <div className="flex items-center gap-2 justify-end text-emerald-600 font-bold">
                        <Calendar size={16} /> {generatedAt}
                    </div>
                    <p className="text-xs text-slate-400 mt-1">Generated by DataCBS System</p>
                </div>
            </div>

            {/* KPI SUMMARY GRID */}
            <div className="grid grid-cols-4 gap-4 mb-8">
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
                    <div className="flex items-center gap-2 mb-2 text-slate-500 text-xs font-bold uppercase"><Scale size={14} /> Total Netto</div>
                    <div className="text-2xl font-black text-slate-800">{stats.totalNetto.toLocaleString('id-ID')} <span className="text-xs font-normal">KG</span></div>
                </div>
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
                    <div className="flex items-center gap-2 mb-2 text-slate-500 text-xs font-bold uppercase"><Truck size={14} /> Total Truk</div>
                    <div className="text-2xl font-black text-slate-800">{stats.totalTruk} <span className="text-xs font-normal">Unit</span></div>
                </div>
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
                    <div className="flex items-center gap-2 mb-2 text-slate-500 text-xs font-bold uppercase"><TrendingUp size={14} /> Rata-rata BJR</div>
                    <div className="text-2xl font-black text-amber-600">{typeof stats.avgBJR === 'number' ? stats.avgBJR.toFixed(2) : stats.avgBJR} <span className="text-xs font-normal">KG</span></div>
                </div>
                <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
                    <div className="flex items-center gap-2 mb-2 text-slate-500 text-xs font-bold uppercase"><AlertTriangle size={14} /> Grade C (Low)</div>
                    <div className="text-2xl font-black text-red-600">{gradeCIssues.length} <span className="text-xs font-normal">Tiket</span></div>
                </div>
            </div>

            {/* CHARTS ROW */}
            <div className="grid grid-cols-2 gap-6 mb-8">
                {/* Trend Chart */}
                <div className="p-4 border border-slate-200 rounded-xl">
                    <h3 className="font-bold text-sm mb-4 border-l-4 border-emerald-500 pl-2">Tren Penerimaan (KG)</h3>
                    <div className="h-[200px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={chartData.trend}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="displayDate" tick={{ fontSize: 10 }} interval={1} />
                                <YAxis tick={{ fontSize: 10 }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}T`} />
                                <Area type="monotone" dataKey="total" stroke="#059669" fill="#10b981" fillOpacity={0.2} isAnimationActive={false} />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Peak Hours Chart */}
                <div className="p-4 border border-slate-200 rounded-xl">
                    <h3 className="font-bold text-sm mb-4 border-l-4 border-purple-500 pl-2">Jam Sibuk Operasional</h3>
                    <div className="h-[200px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={chartData.peakHours}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="hour" tick={{ fontSize: 10 }} interval={2} />
                                <YAxis tick={{ fontSize: 10 }} />
                                <Bar dataKey="count" fill="#8b5cf6" isAnimationActive={false} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>

            {/* LISTS ROW */}
            <div className="grid grid-cols-2 gap-6 mb-8">
                {/* Top Vendors */}
                <div>
                    <h3 className="font-bold text-sm mb-3 flex items-center gap-2 bg-slate-100 p-2 rounded">
                        <MapPin size={16} /> Top 5 Lokasi / Vendor
                    </h3>
                    <table className="w-full text-sm">
                        <thead className="text-xs text-slate-500 border-b border-slate-200 text-left">
                            <tr>
                                <th className="pb-2">Lokasi</th>
                                <th className="pb-2 text-right">Total Netto</th>
                            </tr>
                        </thead>
                        <tbody>
                            {topSuppliers.slice(0, 5).map((vendor, idx) => (
                                <tr key={idx} className="border-b border-slate-50">
                                    <td className="py-2 font-medium">{vendor.name}</td>
                                    <td className="py-2 text-right font-mono text-emerald-600">{vendor.value.toLocaleString('id-ID')}</td>
                                </tr>
                            ))}
                            {topSuppliers.length === 0 && <tr><td colSpan={2} className="py-2 text-center text-slate-400">Tidak ada data</td></tr>}
                        </tbody>
                    </table>
                </div>

                {/* Grade C Issues */}
                <div>
                    <h3 className="font-bold text-sm mb-3 flex items-center gap-2 bg-red-50 text-red-700 p-2 rounded">
                        <AlertTriangle size={16} /> Isu Kualitas (Grade C) Teratas
                    </h3>
                    <table className="w-full text-sm">
                        <thead className="text-xs text-slate-500 border-b border-slate-200 text-left">
                            <tr>
                                <th className="pb-2">Nopol</th>
                                <th className="pb-2">Lokasi</th>
                                <th className="pb-2 text-right">BJR</th>
                            </tr>
                        </thead>
                        <tbody>
                            {gradeCIssues.slice(0, 5).map((t, idx) => {
                                const bjr = t.janjang > 0 ? (t.netto / t.janjang) : 0;
                                return (
                                    <tr key={idx} className="border-b border-slate-50">
                                        <td className="py-2 font-bold">{t.nopol}</td>
                                        <td className="py-2 text-xs text-slate-500">{t.lokasi.substring(0, 15)}</td>
                                        <td className="py-2 text-right font-mono text-red-600 font-bold">{bjr.toFixed(2)}</td>
                                    </tr>
                                );
                            })}
                            {gradeCIssues.length === 0 && <tr><td colSpan={3} className="py-2 text-center text-slate-400">Kualitas Aman (Nihil)</td></tr>}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* AI INSIGHT SECTION */}
            <div className="mt-auto border-2 border-indigo-100 rounded-xl p-6 bg-indigo-50/50">
                <h3 className="font-bold text-indigo-700 mb-2 flex items-center gap-2">
                    <BrainCircuit size={20} /> Gemini AI Executive Summary
                </h3>
                {aiInsight ? (
                    <p className="text-sm leading-relaxed text-slate-700 text-justify font-medium">
                        {aiInsight}
                    </p>
                ) : (
                    <p className="text-sm text-slate-400 italic">Analisis AI belum digenerate pada dashboard.</p>
                )}
            </div>

            {/* FOOTER */}
            <div className="absolute bottom-6 left-0 w-full text-center">
                <p className="text-[10px] text-slate-300 uppercase tracking-widest">Confidential Document • Internal Use Only</p>
            </div>

        </div>
    );
};

export default ExecutiveReportTemplate;